# put common definitions in here
CC              = gcc
PRJCFLAGS       = -Wall -Werror -Wextra -pedantic -std=c99 -g
LD              = gcc
LDFLAGS         = -lm
RM              = rm
ECHO            = echo

.SILENT :
